version: '3'

services:
    nginx:
        build: ./nginx
        links:
            - node1:node1
        ports:
            - "80:80"
    node1:
        build: ./node
        depends_on: 
            - db
        links:
            - db
        volumes:
            - ./node/src:/app/src
        ports:
            - "8080"
            - "56745:56745"
    db:
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "4306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: express
            MYSQL_DATABASE: express
            MYSQL_USER: express
            MYSQL_PASSWORD: express

volumes:
    dbdata: