version: '3'

services:
    nginx:
        build: ./nginx
        links:
            - node1:node1
        ports:
            - "80:80"
    node1:
        build: ./node
        depends_on: 
            - db
        links:
            - db
        volumes:
            - ./node/src:/app/src
        ports:
            - "8080"
            - "56745:56745"
    db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        image: mongo-express
        restart: always
        links:
            - db
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: db
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example